import random

# Dictionary negara dan ibu kota (bisa ditambah sesuai kebutuhan)
ibu_kota_ke_negara = {
    "Afganistan": "Kabul",
    "Afrika Selatan": "Pretoria",
    "Albania": "Tirana",
    "Aljazair": "Algiers",
    "Amerika Serikat": "Washington D.C.",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Antigua dan Barbuda": "Saint John's",
    "Arab Saudi": "Riyadh",
    "Argentina": "Buenos Aires",
    "Armenia": "Yerevan",
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Azerbaijan": "Baku",
    "Bahama": "Nassau",
    "Bahrain": "Manama",
    "Bangladesh": "Dhaka",
    "Barbados": "Bridgetown",
    "Belanda": "Amsterdam",
    "Belarusia": "Minsk",
    "Belgia": "Brussels",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bhutan": "Thimphu",
    "Bolivia": "Sucre (de jure), La Paz (seat of government)",
    "Bosnia dan Herzegovina": "Sarajevo",
    "Botswana": "Gaborone",
    "Brasil": "Brasília",
    "Brunei Darussalam": "Bandar Seri Begawan",
    "Bulgaria": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Ceko": "Prague",
    "Chile": "Santiago",
    "China": "Beijing",
    "Denmark": "Kopenhagen",
    "Djibouti": "Djibouti",
    "Dominika": "Roseau",
    "Ekuador": "Quito",
    "Ekuatorial Guinea": "Malabo (de jure), Oyala (seat of government)",
    "El Salvador": "San Salvador",
    "Eritrea": "Asmara",
    "Estonia": "Tallinn",
    "Eswatini": "Mbabane (administrative), Lobamba (legislative, royal)",
    "Ethiopia": "Addis Ababa",
    "Fiji": "Suva",
    "Finlandia": "Helsinki",
    "Prancis": "Paris",
    "Gabon": "Libreville",
    "Gambia": "Banjul",
    "Georgia": "Tbilisi",
    "Jerman": "Berlin",
    "Ghana": "Accra",
    "Yunani": "Athens",
    "Grenada": "Saint George's",
    "Guatemala": "Guatemala City",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haiti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Hungaria": "Budapest",
    "Islandia": "Reykjavik",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Irak": "Baghdad",
    "Irlandia": "Dublin",
    "Israel": "Yerusalem",
    "Italia": "Roma",
    "Jamaika": "Kingston",
    "Jepang": "Tokyo",
    "Jordania": "Amman",
    "Kazakhstan": "Nur-Sultan",
    "Kenya": "Nairobi",
    "Kiribati": "Tarawa",
    "Kosovo": "Pristina",
    "Kuwait": "Kuwait City",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Latvia": "Riga",
    "Libanon": "Beirut",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripoli",
    "Liechtenstein": "Vaduz",
    "Lituania": "Vilnius",
    "Luxembourg": "Luxembourg City",
    "Madagaskar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malaysia": "Kuala Lumpur",
    "Maladewa": "Malé",
    "Mali": "Bamako",
    "Malta": "Valletta",
    "Marshall Islands": "Majuro",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port Louis",
    "Meksiko": "Mexico City",
    "Mikronesia": "Palikir",
    "Moldova": "Chisinau",
    "Monako": "Monaco",
    "Mongolia": "Ulaanbaatar",
    "Montenegro": "Podgorica",
    "Maroko": "Rabat",
    "Mozambik": "Maputo",
    "Myanmar": "Naypyidaw",
    "Namibia": "Windhoek",
    "Nauru": "Yaren District (de facto)",
    "Nepal": "Kathmandu",
    "Belanda": "Amsterdam",
    "Selandia Baru": "Wellington",
    "Nikaragua": "Managua",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "Korea Utara": "Pyongyang",
    "Makedonia Utara": "Skopje",
    "Norwegia": "Oslo",
    "Oman": "Muscat",
    "Pakistan": "Islamabad",
    "Palau": "Ngerulmud",
    "Palestina": "Yerusalem (Timur)",
    "Panama": "Panama City",
    "Papua Nugini": "Port Moresby",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Filipina": "Manila",
    "Polandia": "Warsawa",
    "Portugal": "Lisbon",
    "Qatar": "Doha",
    "Rumania": "Bukares",
    "Rusia": "Moskwa",
    "Rwanda": "Kigali",
    "Saint Kitts dan Nevis": "Basseterre",
    "Saint Lucia": "Castries",
    "Saint Vincent dan Grenadines": "Kingstown",
    "Samoa": "Apia",
}

def main():
    print("🌍 Selamat datang di Game Tebak Negara dari Ibu Kotanya!")
    print("Ketik 'exit' kapan saja untuk keluar dari permainan.\n")

    skor = 0
    pertanyaan = list(ibu_kota_ke_negara.items())
    random.shuffle(pertanyaan)

    for ibu_kota, negara in pertanyaan:
        jawaban = input(f"Apa nama negara dengan ibu kota '{ibu_kota}'? ").strip()

        if jawaban.lower() == 'exit':
            break
        elif jawaban.lower() == negara.lower():
            print("✅ Benar!\n")
            skor += 1
        else:
            print(f"❌ Salah. Jawaban yang benar adalah: {negara}\n")

    print(f"\n🏁 Permainan selesai! Skor akhirmu: {skor}/{len(pertanyaan)}")
    print("Terima kasih sudah bermain! 🎉")

if __name__ == "__main__":
    main()
